library ANCConcepts

codesystem "ANC.B5": 'http://smart.who.int/anc-test/CodeSystem/ANC.B5'

valueset "Danger Signs": 'http://smart.who.int/anc-test/ValueSet/ANC.B5.DE48'
valueset "Danger Signs - No Danger Signs": 'http://smart.who.int/anc-test/ValueSet/ANC.B5.DE49'
valueset "Danger Signs Choices": 'http://smart.who.int/anc-test/ValueSet/ANC.B5.DE50'
valueset "Danger Signs - Central cynosis": 'http://smart.who.int/anc-test/ValueSet/ANC.B5.DE51'
valueset "Antenatal care case": 'http://smart.who.int/anc-test/ValueSet/ANC.Care.Case'
valueset "Antenatal care contact": 'http://smart.who.int/anc-test/ValueSet/ANC.Care.Contact'
valueset "Reason for closing ANC record": 'http://smart.who.int/anc-test/ValueSet/ANC.End.1'
valueset "Qualifying Reason for closing ANC record Choices": 'http://smart.who.int/anc-test/ValueSet/ANC.End.2'